# Generate Code Fix Changelog
# Analyzes git diff and creates a summary of changes

param()

$ErrorActionPreference = "Continue"
$CHANGELOG_FILE = "CODE_FIX_CHANGELOG.md"

# Check if there are any changes
$hasChanges = git diff --quiet 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "Generating changelog from git diff..."
    
    # Get all changed files
    $changedFiles = git diff --name-only
    
    # Count files changed by extension
    $jsFiles = $changedFiles | Where-Object { $_ -match '\.(js|jsx|mjs)$' }
    $cssFiles = $changedFiles | Where-Object { $_ -match '\.css$' }
    $htmlFiles = $changedFiles | Where-Object { $_ -match '\.html$' }
    $pyFiles = $changedFiles | Where-Object { $_ -match '\.py$' }
    $psFiles = $changedFiles | Where-Object { $_ -match '\.(ps1|psm1)$' }
    $solFiles = $changedFiles | Where-Object { $_ -match '\.sol$' }
    
    $JS_COUNT = ($jsFiles | Measure-Object).Count
    $CSS_COUNT = ($cssFiles | Measure-Object).Count
    $HTML_COUNT = ($htmlFiles | Measure-Object).Count
    $PY_COUNT = ($pyFiles | Measure-Object).Count
    $PS_COUNT = ($psFiles | Measure-Object).Count
    $SOL_COUNT = ($solFiles | Measure-Object).Count
    
    $TOTAL_COUNT = $JS_COUNT + $CSS_COUNT + $HTML_COUNT + $PY_COUNT + $PS_COUNT + $SOL_COUNT
    
    # Get current timestamp
    $TIMESTAMP = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss UTC")
    
    # Create changelog header
    $changelog = @"
# Code Fix Changelog

**Generated:** $TIMESTAMP

## Summary of Changes

This changelog documents automated code quality fixes applied across the repository.

### Files Modified by Language

- **JavaScript/JSX/MJS:** $JS_COUNT file(s)
- **CSS:** $CSS_COUNT file(s)
- **HTML:** $HTML_COUNT file(s)
- **Python:** $PY_COUNT file(s)
- **PowerShell:** $PS_COUNT file(s)
- **Solidity:** $SOL_COUNT file(s)

**Total files modified:** $TOTAL_COUNT

### Tools Used

"@
    
    # Add tool details based on which files were changed
    if ($JS_COUNT -gt 0) {
        $changelog += @"

#### JavaScript/JSX/MJS
- **ESLint**: Code linting and auto-fixes
- **Prettier**: Code formatting

"@
    }
    
    if ($CSS_COUNT -gt 0) {
        $changelog += @"

#### CSS
- **Stylelint**: CSS linting and auto-fixes

"@
    }
    
    if ($HTML_COUNT -gt 0) {
        $changelog += @"

#### HTML
- **HTMLHint**: HTML validation
- **Prettier**: HTML formatting

"@
    }
    
    if ($PY_COUNT -gt 0) {
        $changelog += @"

#### Python
- **Black**: Code formatting (PEP 8 compliant)
- **Flake8**: Code linting

"@
    }
    
    if ($PS_COUNT -gt 0) {
        $changelog += @"

#### PowerShell
- **PSScriptAnalyzer**: Static analysis and best practices

"@
    }
    
    if ($SOL_COUNT -gt 0) {
        $changelog += @"

#### Solidity
- **solhint**: Solidity linting and auto-fixes

"@
    }
    
    # Add changed files list
    $changelog += @"

### Changed Files

"@
    
    foreach ($file in $changedFiles) {
        $changelog += "- ``$file```n"
    }
    
    # Add diff stats
    $changelog += @"

### Statistics

"@
    
    $diffStats = git diff --stat
    $changelog += $diffStats
    $changelog += "`n"
    
    # Add footer
    $changelog += @"

---

## Verification

All changes have been applied following the allowlist/denylist policy:

**Allowlist (files that CAN be modified):**
- ``**/*.{js,jsx,mjs,css,html,py,ps1,psm1,sol}``

**Denylist (files that CANNOT be modified):**
- ``.github/**``, ``.devcontainer/**``
- ``**/Dockerfile``, ``**/docker/**``
- ``**/infra/**``, ``**/terraform/**``, ``**/ansible/**``
- ``**/deploy/**``, ``**/wrangler.toml``
- ``**/cloudflare*.{toml,yml,yaml}``, ``**/pages*.{yml,yaml}``
- ``**/.vscode/**``

**Guarantee:** No infrastructure files were modified by this automation.

---

*Generated by WIRED CHAOS Code Quality Fix Automation*
"@
    
    # Write changelog to file
    $changelog | Out-File -FilePath $CHANGELOG_FILE -Encoding UTF8
    
    Write-Host "✓ Changelog generated: $CHANGELOG_FILE" -ForegroundColor Green
} else {
    Write-Host "No changes detected. Skipping changelog generation." -ForegroundColor Yellow
}
