#!/bin/bash
# Generate Code Fix Changelog
# Analyzes git diff and creates a summary of changes

set -e

CHANGELOG_FILE="CODE_FIX_CHANGELOG.md"

# Check if there are any changes
if ! git diff --quiet; then
    echo "Generating changelog from git diff..."
    
    # Count files changed by extension
    JS_COUNT=$(git diff --name-only | grep -E '\.(js|jsx|mjs)$' | wc -l)
    CSS_COUNT=$(git diff --name-only | grep -E '\.css$' | wc -l)
    HTML_COUNT=$(git diff --name-only | grep -E '\.html$' | wc -l)
    PY_COUNT=$(git diff --name-only | grep -E '\.py$' | wc -l)
    PS_COUNT=$(git diff --name-only | grep -E '\.(ps1|psm1)$' | wc -l)
    SOL_COUNT=$(git diff --name-only | grep -E '\.sol$' | wc -l)
    
    # Get current timestamp
    TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
    
    # Create changelog
    cat > "$CHANGELOG_FILE" << EOF
# Code Fix Changelog

**Generated:** $TIMESTAMP

## Summary of Changes

This changelog documents automated code quality fixes applied across the repository.

### Files Modified by Language

- **JavaScript/JSX/MJS:** $JS_COUNT file(s)
- **CSS:** $CSS_COUNT file(s)
- **HTML:** $HTML_COUNT file(s)
- **Python:** $PY_COUNT file(s)
- **PowerShell:** $PS_COUNT file(s)
- **Solidity:** $SOL_COUNT file(s)

**Total files modified:** $((JS_COUNT + CSS_COUNT + HTML_COUNT + PY_COUNT + PS_COUNT + SOL_COUNT))

### Tools Used

EOF

    # Add tool details based on which files were changed
    if [ $JS_COUNT -gt 0 ]; then
        cat >> "$CHANGELOG_FILE" << 'EOF'
#### JavaScript/JSX/MJS
- **ESLint**: Code linting and auto-fixes
- **Prettier**: Code formatting

EOF
    fi
    
    if [ $CSS_COUNT -gt 0 ]; then
        cat >> "$CHANGELOG_FILE" << 'EOF'
#### CSS
- **Stylelint**: CSS linting and auto-fixes

EOF
    fi
    
    if [ $HTML_COUNT -gt 0 ]; then
        cat >> "$CHANGELOG_FILE" << 'EOF'
#### HTML
- **HTMLHint**: HTML validation
- **Prettier**: HTML formatting

EOF
    fi
    
    if [ $PY_COUNT -gt 0 ]; then
        cat >> "$CHANGELOG_FILE" << 'EOF'
#### Python
- **Black**: Code formatting (PEP 8 compliant)
- **Flake8**: Code linting

EOF
    fi
    
    if [ $PS_COUNT -gt 0 ]; then
        cat >> "$CHANGELOG_FILE" << 'EOF'
#### PowerShell
- **PSScriptAnalyzer**: Static analysis and best practices

EOF
    fi
    
    if [ $SOL_COUNT -gt 0 ]; then
        cat >> "$CHANGELOG_FILE" << 'EOF'
#### Solidity
- **solhint**: Solidity linting and auto-fixes

EOF
    fi
    
    # Add changed files list
    cat >> "$CHANGELOG_FILE" << 'EOF'
### Changed Files

EOF
    
    git diff --name-only | while read -r file; do
        echo "- \`$file\`" >> "$CHANGELOG_FILE"
    done
    
    # Add diff stats
    cat >> "$CHANGELOG_FILE" << 'EOF'

### Statistics

EOF
    
    git diff --stat >> "$CHANGELOG_FILE"
    
    # Add footer
    cat >> "$CHANGELOG_FILE" << 'EOF'

---

## Verification

All changes have been applied following the allowlist/denylist policy:

**Allowlist (files that CAN be modified):**
- `**/*.{js,jsx,mjs,css,html,py,ps1,psm1,sol}`

**Denylist (files that CANNOT be modified):**
- `.github/**`, `.devcontainer/**`
- `**/Dockerfile`, `**/docker/**`
- `**/infra/**`, `**/terraform/**`, `**/ansible/**`
- `**/deploy/**`, `**/wrangler.toml`
- `**/cloudflare*.{toml,yml,yaml}`, `**/pages*.{yml,yaml}`
- `**/.vscode/**`

**Guarantee:** No infrastructure files were modified by this automation.

---

*Generated by WIRED CHAOS Code Quality Fix Automation*
EOF
    
    echo "✓ Changelog generated: $CHANGELOG_FILE"
else
    echo "No changes detected. Skipping changelog generation."
fi
