name = "wired-chaos-meta"
main = "index.js"
compatibility_date = "2025-09-26"

[env.production]
name = "wired-chaos-meta"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "wired-chaos-meta-staging"
vars = { ENVIRONMENT = "staging" }
