name = "chaoswired"
main = "unified-worker.js"
compatibility_date = "2025-10-01"

# Route patterns for www.wiredchaos.xyz
[[routes]]
pattern = "www.wiredchaos.xyz/school*"
zone_name = "wiredchaos.xyz"

[[routes]]
pattern = "www.wiredchaos.xyz/suite*"
zone_name = "wiredchaos.xyz"

[[routes]]
pattern = "www.wiredchaos.xyz/tax*"
zone_name = "wiredchaos.xyz"

[[routes]]
pattern = "www.wiredchaos.xyz/gamma/*"
zone_name = "wiredchaos.xyz"

[[routes]]
pattern = "www.wiredchaos.xyz/bus/*"
zone_name = "wiredchaos.xyz"

[[routes]]
pattern = "www.wiredchaos.xyz/wl/xp/*"
zone_name = "wiredchaos.xyz"

[[routes]]
pattern = "www.wiredchaos.xyz/admin/flag/llm:circuit"
zone_name = "wiredchaos.xyz"

[[routes]]
pattern = "www.wiredchaos.xyz/api/*"
zone_name = "wiredchaos.xyz"

[[routes]]
pattern = "www.wiredchaos.xyz/health"
zone_name = "wiredchaos.xyz"

[[routes]]
pattern = "www.wiredchaos.xyz/university/*"
zone_name = "wiredchaos.xyz"

[[routes]]
pattern = "www.wiredchaos.xyz/vsp*"
zone_name = "wiredchaos.xyz"

# KV Namespaces
[[kv_namespaces]]
binding = "WIRED_CHAOS_KV"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

[env.production]
name = "chaoswired"
vars = { 
  ENVIRONMENT = "production",
  STUB_MODE = "false",
  AUTO_ROLLBACK = "true",
  NOTION_API_KEY = "",
  GAMMA_API_KEY = "",
  ZAPIER_WEBHOOK_SECRET = "",
  WIX_API_KEY = ""
}

[env.staging]
name = "chaoswired-staging"
vars = { 
  ENVIRONMENT = "staging",
  STUB_MODE = "true",
  AUTO_ROLLBACK = "true",
  NOTION_API_KEY = "",
  GAMMA_API_KEY = "",
  ZAPIER_WEBHOOK_SECRET = "",
  WIX_API_KEY = ""
}
