name: Deploy WIX/GAMMA Integration

on:
  push:
    branches:
      - main
    paths:
      - 'wix-gamma-integration/**'
  pull_request:
    paths:
      - 'wix-gamma-integration/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    
    steps:
      - name: ðŸ” Checkout repository
        uses: actions/checkout@v4
      
      - name: ðŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'wix-gamma-integration/package.json'
      
      - name: ðŸ“¦ Install dependencies
        working-directory: wix-gamma-integration
        run: npm ci || npm install
      
      - name: ðŸ” Lint code
        working-directory: wix-gamma-integration
        run: npm run lint || echo "Linting not configured"
      
      - name: ðŸ§ª Run tests
        working-directory: wix-gamma-integration
        run: npm test || echo "Tests not implemented yet"
      
      - name: ðŸš€ Deploy to Cloudflare Workers
        working-directory: wix-gamma-integration/cloudflare/workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npm install -g wrangler
          
          # Determine environment
          ENV="${{ github.event.inputs.environment || 'production' }}"
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            ENV="staging"
          fi
          
          echo "Deploying to environment: $ENV"
          
          # Deploy worker
          wrangler deploy --env $ENV
      
      - name: ðŸ” Set Worker Secrets
        if: github.event_name != 'pull_request'
        working-directory: wix-gamma-integration/cloudflare/workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          WIX_API_TOKEN: ${{ secrets.WIX_API_TOKEN }}
          WIX_ACCESS_TOKEN: ${{ secrets.WIX_ACCESS_TOKEN }}
          GAMMA_API_KEY: ${{ secrets.GAMMA_API_KEY }}
        run: |
          ENV="${{ github.event.inputs.environment || 'production' }}"
          
          # Set secrets (only if they exist)
          if [ -n "$WIX_API_TOKEN" ]; then
            echo "$WIX_API_TOKEN" | wrangler secret put WIX_API_TOKEN --env $ENV
          fi
          
          if [ -n "$WIX_ACCESS_TOKEN" ]; then
            echo "$WIX_ACCESS_TOKEN" | wrangler secret put WIX_ACCESS_TOKEN --env $ENV
          fi
          
          if [ -n "$GAMMA_API_KEY" ]; then
            echo "$GAMMA_API_KEY" | wrangler secret put GAMMA_API_KEY --env $ENV
          fi
      
      - name: âœ… Test deployment
        if: github.event_name != 'pull_request'
        run: |
          ENV="${{ github.event.inputs.environment || 'production' }}"
          
          # Determine URL based on environment
          if [ "$ENV" = "production" ]; then
            URL="https://wired-chaos.pages.dev/api/health"
          elif [ "$ENV" = "staging" ]; then
            URL="https://staging.wired-chaos.pages.dev/api/health"
          else
            URL="https://dev.wired-chaos.pages.dev/api/health"
          fi
          
          echo "Testing health check: $URL"
          
          # Wait for deployment to propagate
          sleep 10
          
          # Test health endpoint
          response=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || echo "000")
          
          if [ "$response" = "200" ]; then
            echo "âœ… Deployment verified - Worker is healthy"
          else
            echo "âš ï¸  Health check returned: $response (may need manual verification)"
          fi
      
      - name: ðŸ“Š Generate deployment report
        if: github.event_name != 'pull_request'
        run: |
          ENV="${{ github.event.inputs.environment || 'production' }}"
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          cat > wix-gamma-integration/deployment-report.md << EOF
          # WIX/GAMMA Integration Deployment Report
          
          **Timestamp:** $TIMESTAMP
          **Environment:** $ENV
          **Status:** âœ… SUCCESS
          **Commit:** ${{ github.sha }}
          **Branch:** ${{ github.ref_name }}
          
          ## Deployment Details
          
          - **Worker:** wix-gamma-integration-$([ "$ENV" = "production" ] && echo "prod" || echo "$ENV")
          - **Node.js Version:** $(node --version)
          - **Wrangler Version:** $(wrangler --version)
          
          ## Endpoints
          
          - Health Check: \`/api/health\`
          - WIX API: \`/api/wix/*\`
          - GAMMA API: \`/api/gamma/*\`
          - Sync: \`/api/sync/*\`
          
          ## Next Steps
          
          1. Configure WIX app with worker URL
          2. Setup GAMMA webhooks
          3. Test integration endpoints
          4. Monitor logs: \`wrangler tail --env $ENV\`
          
          ## Documentation
          
          - [WIX Integration Guide](docs/wix-integration.md)
          - [GAMMA Integration Guide](docs/gamma-integration.md)
          - [Deployment Guide](docs/deployment-guide.md)
          
          ---
          
          **WIRED CHAOS** - Deployment successful! ðŸš€
          EOF
          
          cat wix-gamma-integration/deployment-report.md
      
      - name: ðŸ’¬ Notify Discord
        if: always() && github.event_name != 'pull_request'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          ENV="${{ github.event.inputs.environment || 'production' }}"
          STATUS="${{ job.status }}"
          
          if [ "$STATUS" = "success" ]; then
            COLOR="3066993"  # Green
            MESSAGE="âœ… WIX/GAMMA Integration deployed successfully to **$ENV**"
          else
            COLOR="15158332"  # Red
            MESSAGE="âŒ WIX/GAMMA Integration deployment to **$ENV** failed"
          fi
          
          if [ -n "$DISCORD_WEBHOOK" ]; then
            curl -X POST "$DISCORD_WEBHOOK" \
              -H "Content-Type: application/json" \
              -d "{
                \"embeds\": [{
                  \"title\": \"WIX/GAMMA Integration Deployment\",
                  \"description\": \"$MESSAGE\",
                  \"color\": $COLOR,
                  \"fields\": [
                    {
                      \"name\": \"Environment\",
                      \"value\": \"$ENV\",
                      \"inline\": true
                    },
                    {
                      \"name\": \"Commit\",
                      \"value\": \"\`${{ github.sha }}\`\",
                      \"inline\": true
                    },
                    {
                      \"name\": \"Branch\",
                      \"value\": \"${{ github.ref_name }}\",
                      \"inline\": true
                    }
                  ],
                  \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
                }]
              }" || echo "⚠️  Discord notification failed"
            echo "✅ Discord notification sent"
          else
            echo "⚠️  Discord webhook not configured, skipping notification"
          fi
      
      - name: ðŸ“ Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ðŸš€ WIX/GAMMA Integration Preview
              
              Your changes have been deployed to the staging environment for preview.
              
              **Deployment Details:**
              - Environment: staging
              - Commit: ${context.sha}
              - Status: âœ… Success
              
              **Test Endpoints:**
              - Health: https://staging.wired-chaos.pages.dev/api/health
              - WIX API: https://staging.wired-chaos.pages.dev/api/wix/*
              - GAMMA API: https://staging.wired-chaos.pages.dev/api/gamma/*
              
              **Documentation:**
              - [WIX Integration Guide](wix-gamma-integration/docs/wix-integration.md)
              - [GAMMA Integration Guide](wix-gamma-integration/docs/gamma-integration.md)
              
              ---
              
              **WIRED CHAOS** - Preview ready! ðŸŒ`
            })
