name: PR Run Automation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  ci-and-smoke-test:
    runs-on: ubuntu-latest
    name: CI and Smoke Test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci --legacy-peer-deps

      - name: Run CI tests
        run: npm run ci

      - name: Run Smoke Tests
        if: success()
        run: |
          echo "🚀 Running smoke tests..."
          # Test endpoints that should be available
          npm run test || true
          echo "✅ Smoke tests completed"

      - name: Upload test artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            frontend/build/
            *.log
        continue-on-error: true

  notify:
    runs-on: ubuntu-latest
    needs: [ci-and-smoke-test]
    if: always()
    
    steps:
      - name: Notify Discord
        if: env.DISCORD_WEBHOOK != ''
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          STATUS="success"
          if [ "${{ needs.ci-and-smoke-test.result }}" != "success" ]; then
            STATUS="failure"
          fi
          
          if [ -n "$DISCORD_WEBHOOK" ]; then
            curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"[WIRED CHAOS] PR #${{ github.event.number }}: '${{ github.event.pull_request.title }}' status: $STATUS\"}" \
              "$DISCORD_WEBHOOK"
          else
            echo "Discord webhook not configured, skipping notification"
          fi
        continue-on-error: true

      - name: Notify Telegram
        if: env.TELEGRAM_BOT_TOKEN != ''
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          STATUS="success"
          if [ "${{ needs.ci-and-smoke-test.result }}" != "success" ]; then
            STATUS="failure"
          fi
          
          if [ -n "$TELEGRAM_BOT_TOKEN" ] && [ -n "$TELEGRAM_CHAT_ID" ]; then
            MESSAGE="[WIRED CHAOS] PR #${{ github.event.number }}: '${{ github.event.pull_request.title }}' status: $STATUS"
            curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
              -d "chat_id=$TELEGRAM_CHAT_ID" \
              -d "text=$MESSAGE"
          else
            echo "Telegram bot not configured, skipping notification"
          fi
        continue-on-error: true

      - name: Notify wiredchaos.xyz group page
        if: env.GROUP_PAGE_WEBHOOK != ''
        env:
          GROUP_PAGE_WEBHOOK: ${{ secrets.GROUP_PAGE_WEBHOOK }}
        run: |
          STATUS="success"
          if [ "${{ needs.ci-and-smoke-test.result }}" != "success" ]; then
            STATUS="failure"
          fi
          
          if [ -n "$GROUP_PAGE_WEBHOOK" ]; then
            curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"pr_number\": \"${{ github.event.number }}\", \"title\": \"${{ github.event.pull_request.title }}\", \"status\": \"$STATUS\"}" \
              "$GROUP_PAGE_WEBHOOK"
          else
            echo "Group page webhook not configured, skipping notification"
          fi
        continue-on-error: true

  cache-purge:
    runs-on: ubuntu-latest
    needs: [ci-and-smoke-test]
    if: needs.ci-and-smoke-test.result == 'success'
    
    steps:
      - name: Purge Cloudflare Cache
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          if [ -n "$CLOUDFLARE_ZONE_ID" ] && [ -n "$CLOUDFLARE_API_TOKEN" ]; then
            echo "🧹 Purging Cloudflare cache..."
            curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -H "Content-Type: application/json" \
              --data '{"purge_everything":true}'
            echo "✅ Cache purge completed"
          else
            echo "Cloudflare credentials not configured, skipping cache purge"
          fi
        continue-on-error: true

  auto-merge:
    runs-on: ubuntu-latest
    needs: [ci-and-smoke-test]
    if: |
      needs.ci-and-smoke-test.result == 'success' &&
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'automerge')
    
    steps:
      - name: Enable auto-merge
        run: |
          echo "🤖 Auto-merge conditions met for dependabot PR"
          gh pr merge ${{ github.event.number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true