name: 🔧 Worker Deploy (Cloudflare Worker)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'wrangler.toml'
      - '.github/workflows/worker-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        # Worker doesn't need dependencies installed at root
        echo "Skipping npm install - worker has no build dependencies"
      continue-on-error: true

    - name: Security audit
      run: |
        echo "Skipping security audit - worker deployment only"
      continue-on-error: true

    - name: Build
      run: |
        # Worker is plain JavaScript, no build step needed
        echo "Skipping build - worker uses plain JavaScript"
      continue-on-error: true

    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        workingDirectory: 'src'
        command: deploy --env production
        
    - name: Update deployment status
      run: |
        echo "⚡ Worker deployed successfully!"
        echo "Worker URL: https://wired-chaos-worker.your-account.workers.dev"